using DemoDatabaseCompare.EntityFrameworkCore;
using Xunit;

namespace DemoDatabaseCompare.EntityFrameworkCore;

public class DemoDatabaseCompareEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<DemoDatabaseCompareEntityFrameworkCoreFixture>
{

}
